# Exported from Render on 2024-10-11T21:47:45Z
services:
- type: web
  name: iac_demo_version2
  runtime: python
  repo: https://github.com/fernandospm/iac_demo
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 app.py
version: "1"
